# Generated by Django 5.0.3 on 2024-05-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
