# Generated by Django 5.0.3 on 2024-05-10 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0002_alter_supply_order_date'),
        ('medicine_store', '0002_alter_medicine_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='departpment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drug.drugdepartment'),
        ),
        migrations.AddField(
            model_name='medicineconsumption',
            name='departpment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drug.drugdepartment'),
        ),
    ]
