# Generated by Django 5.0.3 on 2024-05-16 22:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_admission',
            name='regno',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
