# Generated by Django 5.0.3 on 2024-05-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipd', '0002_patient_admission_regno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_admission',
            name='appointment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient_admission',
            name='discharge_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
