# Generated by Django 5.0.3 on 2024-05-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipd', '0003_alter_patient_admission_appointment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_admission',
            name='discharge',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patient_admission',
            name='regno',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
