# Generated by Django 5.0.3 on 2024-05-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipd', '0004_patient_admission_discharge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_admission',
            name='death',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient_admission',
            name='lama',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
