# Generated by Django 5.0.3 on 2024-05-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipd', '0006_patient_admission_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_admission',
            name='dr_reg_no',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
