# Generated by Django 5.0.3 on 2024-05-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardiology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardiology',
            name='age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cardiology',
            name='gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
