# Generated by Django 5.0.3 on 2024-05-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0003_blooddonate_add_date_blooddonate_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodstock',
            name='blood_type',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
