# Generated by Django 5.0.3 on 2024-05-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='data_add',
            field=models.CharField(blank=True, default='false', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='data_delete',
            field=models.CharField(blank=True, default='false', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='data_edit',
            field=models.CharField(blank=True, default='false', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='data_view',
            field=models.CharField(blank=True, default='false', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='main_department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
