# Generated by Django 5.0.3 on 2024-05-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
