# Generated by Django 5.0.3 on 2024-04-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0002_alter_order_order_id_alter_productsupply_batch_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpurchase',
            name='batch_no',
            field=models.CharField(max_length=255),
        ),
    ]
