# Generated by Django 5.0.3 on 2024-05-12 12:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0002_alter_supply_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supply',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
