# Generated by Django 5.0.3 on 2024-05-06 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0002_radiology_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiology',
            name='sub_unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
