# Generated by Django 5.0.3 on 2024-05-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0002_alter_radiology_add_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_unit_iid', models.CharField(default='', editable=False, max_length=8, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('sub_unit', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
