# Generated by Django 5.0.3 on 2024-05-06 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0003_radiology_sub_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigation',
            name='investigation_unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
