# Generated by Django 5.0.3 on 2024-05-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0003_subunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiology',
            name='investigations',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
