# Generated by Django 5.0.3 on 2024-05-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0004_radiology_investigations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radiology',
            name='investigation',
        ),
        migrations.AddField(
            model_name='radiology',
            name='investigation',
            field=models.ManyToManyField(blank=True, null=True, to='radiology.investigation'),
        ),
    ]
