# Generated by Django 5.0.3 on 2024-05-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0006_remove_radiology_investigation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radiology',
            name='investigation',
        ),
        migrations.AddField(
            model_name='radiology',
            name='investigation',
            field=models.ManyToManyField(blank=True, null=True, to='radiology.investigation'),
        ),
    ]
