# Generated by Django 5.0.3 on 2024-05-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productconsumption_indent_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sp_order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sp_order_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productconsumption',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productconsumption',
            name='sp_order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productconsumption',
            name='sp_order_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
