# Generated by Django 5.0.3 on 2024-05-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productconsumption',
            name='quantity_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
